# Generated by Django 3.2.13 on 2024-05-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
